app:
   num-threads: 2
   stress-method: fatorial
   
loop:
   count: 999999999999999
   maxCount: 999999999999999

factorial:
   number: 10

logging:
  level:
    br:
      com:
        paxtecnologia: DEBUG
